name: Windows Build (Faster)
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ Fraze-glow-camera ]
  pull_request:
    branches: [ Fraze-glow-camera ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    runs-on: windows-latest
    permissions:
        contents: write
        actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Restore Previous Cache
        id: cache-debug-build-windows-restore
        uses: actions/cache/restore@main
        with:
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
          key: cache-windows-build

      - name: Installing Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 > /dev/null --quiet
          haxelib install hmm --quiet
          haxelib run hmm install
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc

     - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Building
        run: haxelib run lime build windows --app-version="4.0.0-${{github.run_id}}"

      - name: Clear Previous Cache
        uses: actions/github-script@main
        with:
          script: |
            try {
            	const caches = await github.rest.actions.getActionsCacheList({
            		owner: context.repo.owner,
            		repo: context.repo.repo,
            	})
            	if (typeof caches.data.actions_caches != null && caches.data.actions_caches.length > 0) {
            		for (const cache of caches.data.actions_caches) {
            			if (cache.key == "cache-windows-build") {
            				console.log('Clearing ' + cache.key + '...')
            				await github.rest.actions.deleteActionsCacheById({
            					owner: context.repo.owner,
            					repo: context.repo.repo,
            					cache_id: cache.id,
            				})
            				console.log("Previous Cache Cleared!")
            			}
            		}
            	}
            } catch (error) {
            	console.log(error.message);
            }

      - name: Save Current Cache
        id: cache-release-build-windows-save
        uses: actions/cache/save@main
        with:
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
          key: cache-windows-build

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: MoonEngine-Windows
          path: export/release/windows/bin
          if-no-files-found: warn